### ISSUE TITLE
Write a quick sort algorithm to sort an array

### ISSUE THREAD

**Issue by virat780** [virat780/DSA-Rockerz#12]

**Comment by AjaySahani942** [comment]
can you assign it to me @virat780

**Comment by Code-Techy** [comment]
## Greetings , **`@virat780 `** 
> **I was looking for a repository to contribute to open source and found this one.**
**Can you assign this to me? I'm familiar with the *CPP Programming* . and I would love to do it.**

_-Regards, thanks._

**Comment by virat780** [comment]
Merged @AjaySahani942
