### ISSUE TITLE
Write a binary search program to search a element from a sorted array

### ISSUE THREAD

**Issue by virat780** [virat780/DSA-Rockerz#6]

**Comment by void-57** [comment]
hey @virat780  please assign me

**Comment by vaibhv232** [comment]
hello sir, plz assign me this issue

**Comment by virat780** [comment]
assigned to @vaibhv232

**Comment by shreyaa2410** [comment]
hello @virat780 , plz assign me this issue

**Comment by MrJayendra** [comment]
I am interested in this work
Please assign it to me

**Comment by virat780** [comment]
@vaibhv232 merged 👍

**Comment by vaibhv232** [comment]
@virat780  Thanks sir
